---
AWSTemplateFormatVersion: 2010-09-09
Description: Sample CloudFormation template
Parameters: 
  Environment: 
    Type: String
    Description: Environment name

Resources: 
  SampleBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: SampleBucket-${Environment}-${AWS::AccountId}
