---
name: Lint and format

on: push

jobs:
  build:
    name: Lint and format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12.5"]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v4
        with:
          version: '0.39.0'
          enable-cache: true
          cache-prefix: ${{ matrix.python-version }}

      - name: Pin python-version ${{ matrix.python-version }}
        if: steps.setup-rye.outputs.cache-hit != 'true'
        run: rye pin ${{ matrix.python-version }}

      - name: Install dependencies
        if: steps.setup-rye.outputs.cache-hit != 'true'
        run: |
          rye sync

      - name: Run Yaml Linter
        run: |
          rye run yamllint **/*.yaml **/*.yml

      - name: Run CloudFormation Linter
        run: |
          rye run cfn-lint templates/*
